#!/bin/bash
#
#Global vars used on several script 
#
HS_HOME="/opt/helper-scripts"
LOGS="/var/log/syslog /var/log/aut.log"
export LOGS
TIMESTAMP=`date  '+%Y%m%d-%H%M'`
STAMP="`date +%F`"
VIEJO_BACKUP_DIR="/opt/samba/backup"
CURRENT_BACKUP_DIR="/usr/local/backup"
CURRENT_WEEK_BACKUP_DIR="$CURRENT_BACKUP_DIR/current-week"

